# Generated by Django 4.1.4 on 2022-12-19 03:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pagos_v2', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expired_payment',
            name='pay_user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='expired_payments', to='pagos_v2.payment_user'),
        ),
    ]
